FROM node:14-alpine

RUN mkdir -p /app

WORKDIR /app

COPY package*.json ./

RUN npm install

ENV PATH=./node_modules/.bin:$PATH

COPY . ./

# CMD ["npm", "run", "dev"]

CMD ["sh", "./dockers/app/entrypoint.sh"]